FROM python:3.13-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY _requirements ./_requirements
RUN pip install -r _requirements/prod.txt

COPY project ./project

WORKDIR /app/project

EXPOSE 8000

COPY entrypoint.production.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]