services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "8020:8000"

    networks:
      - picklepolls
      
    restart: unless-stopped

networks:
  picklepolls:
    name: picklepolls_network
    driver: bridge
