name: picklepolls

services:
  db:
    image: postgres:18.6-bookworm
    container_name: picklepolls-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - picklepolls-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    image: picklepolls-django-image
    container_name: picklepolls-django
    build:
      context: .
      dockerfile: Dockerfile.prod

    env_file:
      - .env

    ports:
      - "8020:8000"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - picklepolls-network

    restart: always

volumes:
  postgres_data:

networks:
  picklepolls-network:
    name: picklepolls-bridge-network
    driver: bridge
