# Generated by Django 6.0 on 2026-08-13 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="publication_datetime",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="datetime published",
            ),
        ),
    ]
