# Generated by Django 6.0 on 2026-09-24 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_entity_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="entities_admined", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
