name: Continuous Integration Test

on:
  pull_request:
    branches: [production]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: picklepolls_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    env:
      CI: true
      DEBUG: true
      DEBUG_MULTILINE: true
      SECRET_KEY: django-insecure-ui7r8@z1y^geibe_d&ixx(q8zn!_4k-9-dos4dle4)bi$ve%(@
      ALLOWED_HOSTS: localhost,127.0.0.1
      CSRF_TRUSTED_ORIGINS: localhost,127.0.0.1

      POSTGRES_DB: picklepolls_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.13.5"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Verify Firefox and geckodriver
        run: |
          echo "CI=$CI"
          echo "GECKOWEBDRIVER=$GECKOWEBDRIVER"

          firefox --version

          echo "Firefox:"
          which firefox
          readlink -f "$(which firefox)"

          echo "Geckodriver:"
          ls -la "$GECKOWEBDRIVER"
          "$GECKOWEBDRIVER/geckodriver" --version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r _requirements/test.txt

      - name: Print working directory and Tree
        run: |
          echo "Working Directory:"
          pwd

          echo "tree -L 1"
          tree -L 1

          echo "tree -L 2"
          tree -L 2

      - name: Run Pytest tests and Get Coverage Report
        working-directory: project
        env:
          DJANGO_SETTINGS_MODULE: picklepolls.settings.test
        run: |
          coverage run -m pytest -sv -m "not skip_on_ci"
          coverage report
